### PR TITLE
Default prefix

### PR DESCRIPTION
**Pull request by vsizov**
`to_css` method fails because of nil in prefix variable. To be consistent with README it should be changed as this.

### CODE REVIEW

**Comment by mroth** [comment]
Apologies, I hadn't touched this repo in a long while so the Travis CI configuration had succumbed to bit-rot and was failing.  I just fixed this in master -- can you please rebase your branch against master so the integration tests run, and then I will review?  Thanks!

**Comment by vsizov** [comment]
done and green

**Comment by mroth** [comment]
Great!  Thanks so much for your contribution.

**Comment by mroth** [comment]
Released to rubygems.org as `v0.0.2`

**Pull request merged**
